spring:
  application:
    name: AthleteWellnessService

  datasource:
    driver-class-name: org.h2.Driver  # spring.datasource.driver-class-name=org.h2
    url: jdbc:h2:mem:test             # spring.datasource.url=jdbc:h2:mem:test
    username: sa                      # spring.datasource.username=sa
    password: password                # spring.datasource.password=password
  jpa:
    hibernate:
      ddl-auto: update           # spring.jpa.hibernate.ddl-auto=create-drop
    show-sql: true                     # spring.jpa.show-sql=true
    properties:
      hibernate:
        format_sql: true               # spring.jpa.properties.hibernate.format_sql=true
    database-platform: org.hibernate.dialect.H2Dialect  # spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true                    # spring.h2.console.enabled=true
      path: /h2

# server.port = 8080
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
